import assert from "node:assert/strict";
import { after, before, test } from "node:test";
import { OpenAICompatibleAdapter } from "../providers/openai-compatible-adapter";
const originalFetch=globalThis.fetch;
before(()=>{globalThis.fetch=async(input,init)=>{const url=String(input);if(url.endsWith("/models"))return Response.json({data:[{id:"mock-chat"}]});if(url.endsWith("/chat/completions")){const parsed=JSON.parse(String(init?.body));if(parsed.stream){const encoder=new TextEncoder();return new Response(new ReadableStream({start(controller){controller.enqueue(encoder.encode('data: {"choices":[{"delta":{"content":"مرحبا"}}]}\n\n'));controller.enqueue(encoder.encode("data: [DONE]\n\n"));controller.close();}}),{headers:{"content-type":"text/event-stream"}});}return Response.json({id:"mock-1",model:"mock-chat",choices:[{message:{content:"مرحبا"},finish_reason:"stop"}],usage:{prompt_tokens:3,completion_tokens:2,total_tokens:5}});}return new Response(null,{status:404});};});
after(()=>{globalThis.fetch=originalFetch;});
const configuration={id:"provider",type:"openai-compatible",name:"Mock",baseUrl:"https://mock-provider.invalid/v1/",enabled:true,credential:{secret:"test-secret",authType:"bearer" as const},retryCount:0};
test("OpenAI-compatible adapter discovers models and completes",async()=>{const adapter=new OpenAICompatibleAdapter();const models=await adapter.listModels(configuration,{requestId:"test"});assert.equal(models[0]?.id,"mock-chat");const result=await adapter.complete(configuration,{model:"mock-chat",messages:[{role:"user",content:"hello"}]},{requestId:"test"});assert.equal(result.content,"مرحبا");assert.equal(result.usage?.totalTokens,5);});
test("OpenAI-compatible adapter performs real SSE parsing",async()=>{const adapter=new OpenAICompatibleAdapter();let content="";for await(const event of adapter.stream(configuration,{model:"mock-chat",messages:[{role:"user",content:"hello"}]},{requestId:"test"}))if(event.type==="delta")content+=event.content;assert.equal(content,"مرحبا");});
