import { authHeaders, buildUrl, normalizedError, parseSse, providerFetch } from "./http";
import { ProviderError, type AIProviderAdapter, type ProviderConfiguration, type ProviderHealth, type ProviderModel, type ProviderRequestContext, type StreamingResponse, type UnifiedChatRequest, type UnifiedChatResponse } from "./types";
const caps={text:true,vision:true,audio:false,video:false,documents:true,tools:true,structuredOutput:false,embeddings:false,streaming:true};
export class AnthropicAdapter implements AIProviderAdapter{readonly type="anthropic";readonly capabilities={modelDiscovery:true,streaming:true,tools:true,vision:true,audio:false,video:false,documents:true,embeddings:false};
 private headers(c:ProviderConfiguration){const h=authHeaders({...c,credential:{...c.credential!,authType:"api_key_header",headerName:"x-api-key"}});return{"Content-Type":"application/json","anthropic-version":c.apiVersion??"2023-06-01",...h};}
 async validateConfiguration(c:ProviderConfiguration){if(!c.baseUrl||!c.credential?.secret)throw new ProviderError("Anthropic URL and credential are required","INVALID_CONFIGURATION",false,422);}
 async testConnection(c:ProviderConfiguration,x:ProviderRequestContext):Promise<ProviderHealth>{const s=Date.now();try{await this.listModels(c,x);return{ok:true,latencyMs:Date.now()-s,checkedAt:new Date().toISOString()};}catch(e){return{ok:false,latencyMs:Date.now()-s,checkedAt:new Date().toISOString(),errorCode:e instanceof ProviderError?e.code:"UNKNOWN"};}}
 async listModels(c:ProviderConfiguration,x:ProviderRequestContext):Promise<ProviderModel[]>{await this.validateConfiguration(c);const r=await providerFetch(c,buildUrl(c.baseUrl,c.modelsEndpoint??"v1/models"),{headers:this.headers(c)},x);if(!r.ok)throw normalizedError(r.status);const b=await r.json() as{data?:Array<{id:string;display_name?:string}>};return(b.data??[]).map(m=>({id:m.id,name:m.display_name,capabilities:caps}));}
 private body(r:UnifiedChatRequest,stream:boolean){const system=r.messages.filter(m=>m.role==="system").map(m=>typeof m.content==="string"?m.content:"").join("\n");return{model:r.model,max_tokens:r.maxOutputTokens??2048,temperature:r.temperature,system:system||undefined,messages:r.messages.filter(m=>m.role!=="system").map(m=>({role:m.role==="assistant"?"assistant":"user",content:m.content})),tools:r.tools?.map(t=>({name:t.name,description:t.description,input_schema:t.parameters})),stream};}
 async complete(c:ProviderConfiguration,q:UnifiedChatRequest,x:ProviderRequestContext):Promise<UnifiedChatResponse>{const s=Date.now();const r=await providerFetch(c,buildUrl(c.baseUrl,c.chatEndpoint??"v1/messages"),{method:"POST",headers:this.headers(c),body:JSON.stringify(this.body(q,false))},x);const b=await r.json().catch(()=>null) as {id?:string;model?:string;content?:Array<{type:string;text?:string}>;stop_reason?:string;usage?:{input_tokens?:number;output_tokens?:number}}|null;if(!r.ok)throw normalizedError(r.status);return{id:b?.id??crypto.randomUUID(),model:b?.model??q.model,content:b?.content?.filter(v=>v.type==="text").map(v=>v.text??"").join("")??"",finishReason:b?.stop_reason,usage:{inputTokens:b?.usage?.input_tokens,outputTokens:b?.usage?.output_tokens,totalTokens:(b?.usage?.input_tokens??0)+(b?.usage?.output_tokens??0)},latency:{totalMs:Date.now()-s}};}
 async *stream(c:ProviderConfiguration,q:UnifiedChatRequest,x:ProviderRequestContext):StreamingResponse{yield{type:"start"};const r=await providerFetch(c,buildUrl(c.baseUrl,c.chatEndpoint??"v1/messages"),{method:"POST",headers:this.headers(c),body:JSON.stringify(this.body(q,true))},x);if(!r.ok)throw normalizedError(r.status);for await(const d of parseSse(r,v=>(v as {delta?:{text?:string}}).delta?.text??null))yield{type:"delta",content:d};yield{type:"done"};}}
