import { authHeaders, buildUrl, normalizedError, parseSse, providerFetch } from "./http";
import { ProviderError, type AIProviderAdapter, type ProviderConfiguration, type ProviderHealth, type ProviderModel, type ProviderRequestContext, type StreamingResponse, type UnifiedChatRequest, type UnifiedChatResponse } from "./types";
const caps={text:true,vision:false,audio:false,video:false,documents:true,tools:true,structuredOutput:true,embeddings:true,streaming:true};
export class CohereAdapter implements AIProviderAdapter{readonly type="cohere";readonly capabilities={modelDiscovery:true,streaming:true,tools:true,vision:false,audio:false,video:false,documents:true,embeddings:true};
 async validateConfiguration(c:ProviderConfiguration){if(!c.baseUrl||!c.credential?.secret)throw new ProviderError("Cohere URL and credential are required","INVALID_CONFIGURATION",false,422);}
 async testConnection(c:ProviderConfiguration,x:ProviderRequestContext):Promise<ProviderHealth>{const s=Date.now();try{await this.listModels(c,x);return{ok:true,latencyMs:Date.now()-s,checkedAt:new Date().toISOString()};}catch(e){return{ok:false,latencyMs:Date.now()-s,checkedAt:new Date().toISOString(),errorCode:e instanceof ProviderError?e.code:"UNKNOWN"};}}
 async listModels(c:ProviderConfiguration,x:ProviderRequestContext):Promise<ProviderModel[]>{const r=await providerFetch(c,buildUrl(c.baseUrl,c.modelsEndpoint??"v1/models"),{headers:authHeaders(c)},x);if(!r.ok)throw normalizedError(r.status);const b=await r.json() as{models?:Array<{name:string}>};return(b.models??[]).map(m=>({id:m.name,capabilities:caps}));}
 private body(q:UnifiedChatRequest,stream:boolean){return{model:q.model,messages:q.messages.map(m=>({role:m.role==="assistant"?"assistant":m.role==="system"?"system":"user",content:typeof m.content==="string"?m.content:JSON.stringify(m.content)})),temperature:q.temperature,max_tokens:q.maxOutputTokens,stream};}
 async complete(c:ProviderConfiguration,q:UnifiedChatRequest,x:ProviderRequestContext):Promise<UnifiedChatResponse>{const s=Date.now();const r=await providerFetch(c,buildUrl(c.baseUrl,c.chatEndpoint??"v2/chat"),{method:"POST",headers:{"Content-Type":"application/json",...authHeaders(c)},body:JSON.stringify(this.body(q,false))},x);const b=await r.json().catch(()=>null) as {id?:string;message?:{content?:Array<{text?:string}>};finish_reason?:string;usage?:{tokens?:{input_tokens?:number;output_tokens?:number}}}|null;if(!r.ok)throw normalizedError(r.status);return{id:b?.id??crypto.randomUUID(),model:q.model,content:b?.message?.content?.map(p=>p.text??"").join("")??"",finishReason:b?.finish_reason,usage:{inputTokens:b?.usage?.tokens?.input_tokens,outputTokens:b?.usage?.tokens?.output_tokens},latency:{totalMs:Date.now()-s}};}
 async *stream(c:ProviderConfiguration,q:UnifiedChatRequest,x:ProviderRequestContext):StreamingResponse{yield{type:"start"};const r=await providerFetch(c,buildUrl(c.baseUrl,c.chatEndpoint??"v2/chat"),{method:"POST",headers:{"Content-Type":"application/json",...authHeaders(c)},body:JSON.stringify(this.body(q,true))},x);if(!r.ok)throw normalizedError(r.status);for await(const d of parseSse(r,v=>(v as {delta?:{message?:{content?:{text?:string}}}}).delta?.message?.content?.text??null))yield{type:"delta",content:d};yield{type:"done"};}}
