import { buildUrl, normalizedError, parseSse, providerFetch } from "./http";
import { ProviderError, type AIProviderAdapter, type ProviderConfiguration, type ProviderHealth, type ProviderModel, type ProviderRequestContext, type StreamingResponse, type UnifiedChatRequest, type UnifiedChatResponse } from "./types";
const caps={text:true,vision:true,audio:true,video:true,documents:true,tools:true,structuredOutput:true,embeddings:true,streaming:true};
export class GeminiAdapter implements AIProviderAdapter{readonly type="google-gemini";readonly capabilities={modelDiscovery:true,streaming:true,tools:true,vision:true,audio:true,video:true,documents:true,embeddings:true};
 async validateConfiguration(c:ProviderConfiguration){if(!c.baseUrl||!c.credential?.secret)throw new ProviderError("Gemini URL and API key are required","INVALID_CONFIGURATION",false,422);}
 private url(c:ProviderConfiguration,path:string){const u=buildUrl(c.baseUrl,path);u.searchParams.set("key",c.credential!.secret);return u;}
 async testConnection(c:ProviderConfiguration,x:ProviderRequestContext):Promise<ProviderHealth>{const s=Date.now();try{await this.listModels(c,x);return{ok:true,latencyMs:Date.now()-s,checkedAt:new Date().toISOString()};}catch(e){return{ok:false,latencyMs:Date.now()-s,checkedAt:new Date().toISOString(),errorCode:e instanceof ProviderError?e.code:"UNKNOWN"};}}
 async listModels(c:ProviderConfiguration,x:ProviderRequestContext):Promise<ProviderModel[]>{await this.validateConfiguration(c);const r=await providerFetch(c,this.url(c,c.modelsEndpoint??"v1beta/models"),{},x);if(!r.ok)throw normalizedError(r.status);const b=await r.json() as{models?:Array<{name:string;displayName?:string}>};return(b.models??[]).map(m=>({id:m.name.replace(/^models\//,""),name:m.displayName,capabilities:caps}));}
 private body(q:UnifiedChatRequest){return{contents:q.messages.filter(m=>m.role!=="system").map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:typeof m.content==="string"?m.content:JSON.stringify(m.content)}]})),systemInstruction:q.messages.some(m=>m.role==="system")?{parts:[{text:q.messages.filter(m=>m.role==="system").map(m=>m.content).join("\n")}]}:undefined,generationConfig:{temperature:q.temperature,maxOutputTokens:q.maxOutputTokens,responseMimeType:q.responseFormat==="json"?"application/json":undefined}};}
 async complete(c:ProviderConfiguration,q:UnifiedChatRequest,x:ProviderRequestContext):Promise<UnifiedChatResponse>{const s=Date.now();const r=await providerFetch(c,this.url(c,`v1beta/models/${encodeURIComponent(q.model)}:generateContent`),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(this.body(q))},x);const b=await r.json().catch(()=>null) as {candidates?:Array<{content?:{parts?:Array<{text?:string}>};finishReason?:string}>;usageMetadata?:{promptTokenCount?:number;candidatesTokenCount?:number;totalTokenCount?:number}}|null;if(!r.ok)throw normalizedError(r.status);return{id:crypto.randomUUID(),model:q.model,content:b?.candidates?.[0]?.content?.parts?.map(p=>p.text??"").join("")??"",finishReason:b?.candidates?.[0]?.finishReason,usage:{inputTokens:b?.usageMetadata?.promptTokenCount,outputTokens:b?.usageMetadata?.candidatesTokenCount,totalTokens:b?.usageMetadata?.totalTokenCount},latency:{totalMs:Date.now()-s}};}
 async *stream(c:ProviderConfiguration,q:UnifiedChatRequest,x:ProviderRequestContext):StreamingResponse{yield{type:"start"};const u=this.url(c,`v1beta/models/${encodeURIComponent(q.model)}:streamGenerateContent`);u.searchParams.set("alt","sse");const r=await providerFetch(c,u,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(this.body(q))},x);if(!r.ok)throw normalizedError(r.status);for await(const d of parseSse(r,v=>(v as {candidates?:Array<{content?:{parts?:Array<{text?:string}>}}>}).candidates?.[0]?.content?.parts?.map(p=>p.text??"").join("")??null))yield{type:"delta",content:d};yield{type:"done"};}}
