import { getCurrentUser } from "@/lib/auth/guards";
import { createAdminClient } from "@/lib/supabase/admin";
import { serverEnv } from "@/config/env.server";
import { featureFlags } from "@/config/feature-flags";
import { ProviderError } from "@/providers/types";
import { checksum, validateMagic, validateUpload } from "@/services/file-validation";
import { chunkText, extractInlineText } from "@/services/text-processing";
export const dynamic="force-dynamic";
export async function GET(){const user=await getCurrentUser();if(!user)return Response.json({error:{code:"UNAUTHORIZED"}},{status:401});const {data,error}=await createAdminClient().from("files").select("id,original_name,mime_type,extension,size_bytes,status,source,uploaded_at,metadata").eq("owner_user_id",user.id).is("deleted_at",null).order("uploaded_at",{ascending:false}).limit(100);return error?Response.json({error:{code:"DATABASE_ERROR"}},{status:500}):Response.json({data});}
export async function POST(request:Request){if(!featureFlags.FILE_UPLOADS_ENABLED)return Response.json({error:{code:"FEATURE_DISABLED",message:"رفع الملفات غير مفعّل."}},{status:503});const user=await getCurrentUser();if(!user)return Response.json({error:{code:"UNAUTHORIZED"}},{status:401});try{const form=await request.formData();const entries=form.getAll("files");if(!entries.length||entries.length>10)return Response.json({error:{code:"VALIDATION_ERROR",message:"اختر من ملف واحد إلى عشرة ملفات."}},{status:422});const admin=createAdminClient();const uploaded=[];for(const entry of entries){if(!(entry instanceof File))throw new ProviderError("Invalid file","CAPABILITY_UNSUPPORTED",false,422);const {extension}=validateUpload(entry,serverEnv.MAX_UPLOAD_BYTES);const bytes=new Uint8Array(await entry.arrayBuffer());validateMagic(bytes,entry.type);const id=crypto.randomUUID();const path=`${user.id}/${new Date().toISOString().slice(0,10)}/${id}${extension?`.${extension}`:""}`;const digest=await checksum(bytes);const {error:storageError}=await admin.storage.from("chat-attachments").upload(path,bytes,{contentType:entry.type,upsert:false});if(storageError)throw new Error("Storage upload failed");const {data:fileRow,error:fileError}=await admin.from("files").insert({id,owner_user_id:user.id,original_name:entry.name,storage_path:path,mime_type:entry.type,extension,size_bytes:entry.size,checksum:digest,status:"uploaded",source:"chat",metadata:{validation:"mime+signature",antivirus:"not_configured"}}).select("id,original_name,mime_type,size_bytes,status").single();if(fileError){await admin.storage.from("chat-attachments").remove([path]);throw new Error("File metadata save failed");}const text=extractInlineText(bytes,entry.type);if(text!==null){const words=text.trim()?text.trim().split(/\s+/).length:0;const {data:extracted}=await admin.from("file_extracted_contents").insert({file_id:id,text_content:text,word_count:words,metadata:{extractor:"inline-text-v1"}}).select("id").single();const chunks=chunkText(text);if(chunks.length)await admin.from("file_chunks").insert(chunks.map((content,chunk_index)=>({file_id:id,chunk_index,content,token_count:Math.ceil(content.length/4)})));await admin.from("files").update({status:"ready",metadata:{validation:"mime+signature",extractor:"inline-text-v1",chunks:chunks.length,antivirus:"not_configured"}}).eq("id",id);uploaded.push({...fileRow,status:"ready",extractedTextId:extracted?.id});}else{await admin.from("file_processing_jobs").insert({file_id:id,job_type:"extract_text",status:"queued"});uploaded.push({...fileRow,processing:"queued"});}}return Response.json({data:uploaded},{status:201});}catch(error){const p=error instanceof ProviderError?error:null;return Response.json({error:{code:p?.code??"UPLOAD_FAILED",message:p?.message??"تعذر رفع الملف."}},{status:p?.status??500});}}
