import "server-only";
import { createAdminClient } from "@/lib/supabase/admin";
import { providerRegistry } from "@/providers/provider-registry";
import { ProviderError, type StreamingEvent, type UnifiedChatMessage } from "@/providers/types";
import type { ChatRequestInput } from "@/schemas/chat";
import { loadProviderConfiguration } from "./provider-config-service";
import { assertWithinQuota } from "./quota-service";
import { modelCapabilities, validateModelCapabilities } from "./model-capability-service";
import { calculateEstimatedCost } from "./cost-calculator";

type ModelRow={id:string;provider_id:string;model_key:string;model_alias:string|null;display_name:string;enabled:boolean;visible_to_users:boolean;max_message_chars:number;max_output_tokens:number|null;capabilities:unknown;pricing_metadata:unknown;ai_providers:{id:string;name:string;provider_type:string;base_url:string|null;enabled:boolean;chat_endpoint?:string;models_endpoint?:string;api_version?:string|null;timeout_ms?:number;retry_count?:number;configuration?:unknown}};
export async function prepareChat(userId:string,input:ChatRequestInput,signal?:AbortSignal){const admin=createAdminClient();const {data:modelRaw,error:modelError}=await admin.from("ai_models").select("id,provider_id,model_key,model_alias,display_name,enabled,visible_to_users,max_message_chars,max_output_tokens,capabilities,pricing_metadata,ai_providers!inner(*)").eq("id",input.modelId).single();if(modelError||!modelRaw)throw new ProviderError("Model is unavailable","MODEL_UNAVAILABLE",false,404);const model=modelRaw as unknown as ModelRow;if(!model.enabled||!model.visible_to_users||!model.ai_providers.enabled)throw new ProviderError("Model is unavailable","MODEL_UNAVAILABLE",false,409);if(input.message.length>model.max_message_chars)throw new ProviderError("Message is too long for this model","CAPABILITY_UNSUPPORTED",false,422);const capabilities=modelCapabilities(model.capabilities);validateModelCapabilities(capabilities,input.contentParts);await assertWithinQuota(userId,model.id);
 let conversationId=input.conversationId;if(conversationId){const {data}=await admin.from("conversations").select("id").eq("id",conversationId).eq("user_id",userId).eq("status","active").maybeSingle();if(!data)throw new ProviderError("Conversation not found","UNKNOWN",false,404);}else{const {data,error}=await admin.from("conversations").insert({user_id:userId,title:input.message.slice(0,80),selected_model_id:model.id,last_message_at:new Date().toISOString()}).select("id").single();if(error||!data)throw new Error("Could not create conversation");conversationId=data.id;}
 const {data:history}=await admin.from("messages").select("id,role,content,content_parts").eq("conversation_id",conversationId).eq("status","completed").order("sequence_number").limit(100);const sequence=(history?.length??0)+1;const userParts=input.contentParts.length?[{type:"text" as const,text:input.message},...input.contentParts]:[];const {data:userMessage,error:userError}=await admin.from("messages").insert({conversation_id:conversationId,user_id:userId,role:"user",content:input.message,content_parts:userParts,model_id:model.id,provider_id:model.provider_id,parent_message_id:input.parentMessageId,sequence_number:sequence,status:"completed"}).select("id").single();if(userError||!userMessage)throw new Error("Could not save user message");const {data:assistant,error:assistantError}=await admin.from("messages").insert({conversation_id:conversationId,role:"assistant",content:"",content_parts:[],model_id:model.id,provider_id:model.provider_id,parent_message_id:userMessage.id,sequence_number:sequence+1,status:"streaming"}).select("id").single();if(assistantError||!assistant)throw new Error("Could not create assistant message");const {data:run,error:runError}=await admin.from("chat_runs").insert({conversation_id:conversationId,user_message_id:userMessage.id,assistant_message_id:assistant.id,provider_id:model.provider_id,model_id:model.id,status:"streaming",request_metadata:{requestId:crypto.randomUUID(),idempotencyKey:input.idempotencyKey??null}}).select("id,started_at").single();if(runError||!run)throw new Error("Could not create chat run");const configuration=await loadProviderConfiguration(model.ai_providers);const adapter=providerRegistry.get(configuration.type);const messages:UnifiedChatMessage[]=(history??[]).map(m=>({id:m.id,role:m.role as UnifiedChatMessage["role"],content:(m.content_parts as UnifiedChatMessage["content"][])?.length?m.content_parts as UnifiedChatMessage["content"]:m.content}));messages.push({id:userMessage.id,role:"user",content:userParts.length?userParts:input.message});const started=Date.now();
 async function* events():AsyncIterable<StreamingEvent>{let content="";let usage:{inputTokens?:number;outputTokens?:number;totalTokens?:number}={};try{for await(const event of adapter.stream(configuration,{model:model.model_key,messages,temperature:input.temperature,maxOutputTokens:Math.min(input.maxOutputTokens??model.max_output_tokens??4096,model.max_output_tokens??128000),stream:true},{requestId:run!.id,userId,signal})){if(event.type==="delta")content+=event.content??"";if(event.type==="usage"&&event.usage)usage=event.usage;yield event;}const latency=Date.now()-started;const cost=calculateEstimatedCost(usage,model.pricing_metadata);await Promise.all([admin.from("messages").update({content,status:"completed",input_tokens:usage.inputTokens??null,output_tokens:usage.outputTokens??null,total_tokens:usage.totalTokens??null,cost_estimate:cost,latency_ms:latency,updated_at:new Date().toISOString()}).eq("id",assistant!.id),admin.from("chat_runs").update({status:"completed",completed_at:new Date().toISOString(),latency_ms:latency,usage_metadata:usage,estimated_cost:cost}).eq("id",run!.id),admin.from("provider_usage_records").insert({user_id:userId,provider_id:model.provider_id,model_id:model.id,conversation_id:conversationId,chat_run_id:run!.id,input_tokens:usage.inputTokens??0,output_tokens:usage.outputTokens??0,total_tokens:usage.totalTokens??0,estimated_cost:cost}),admin.from("conversations").update({last_message_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",conversationId!)]);}catch(error){const p=error instanceof ProviderError?error:new ProviderError("Generation failed","UNKNOWN",false,500);await Promise.all([admin.from("messages").update({content,status:signal?.aborted?"cancelled":"failed",error_code:p.code,error_message:p.message.slice(0,300)}).eq("id",assistant!.id),admin.from("chat_runs").update({status:signal?.aborted?"cancelled":"failed",completed_at:new Date().toISOString(),error_code:p.code,latency_ms:Date.now()-started}).eq("id",run!.id)]);yield{type:"error",error:{code:p.code,message:safeMessage(p.code),errorId:p.errorId}};}}
 return{conversationId,userMessageId:userMessage.id,assistantMessageId:assistant.id,events:events()};}
function safeMessage(code:string){return code==="RATE_LIMITED"?"تم بلوغ حد الاستخدام، حاول لاحقًا.":code==="TIMEOUT"?"انتهت مهلة المزود.":code==="ABORTED"?"تم إيقاف التوليد.":"تعذر إكمال الرد. احتفظ بمعرّف الخطأ للمراجعة.";}
