import "server-only";
import { createAdminClient } from "@/lib/supabase/admin";
import { resolveProviderCredential } from "./credential-resolver";
import type { ProviderConfiguration } from "@/providers/types";
type ProviderRow={id:string;name:string;provider_type:string;base_url:string|null;enabled:boolean;auth_type?:NonNullable<ProviderConfiguration["credential"]>["authType"];chat_endpoint?:string;models_endpoint?:string;embeddings_endpoint?:string;api_version?:string|null;timeout_ms?:number;retry_count?:number;configuration?:unknown};
export async function loadProviderConfiguration(row:ProviderRow,userId?:string):Promise<ProviderConfiguration>{if(!row.base_url)throw new Error("Provider base URL is missing");const cfg=(row.configuration??{}) as Record<string,unknown>;const authType=row.auth_type??"bearer";return{id:row.id,type:row.provider_type,name:row.name,baseUrl:row.base_url,enabled:row.enabled,chatEndpoint:row.chat_endpoint,modelsEndpoint:row.models_endpoint,embeddingsEndpoint:row.embeddings_endpoint,apiVersion:row.api_version??undefined,timeoutMs:row.timeout_ms,retryCount:row.retry_count,headers:typeof cfg.headers==="object"&&cfg.headers?cfg.headers as Record<string,string>:undefined,credential:await resolveProviderCredential(row.id,userId,{authType,headerName:typeof cfg.headerName==="string"?cfg.headerName:undefined,queryName:typeof cfg.queryName==="string"?cfg.queryName:undefined,username:typeof cfg.username==="string"?cfg.username:undefined})};}
export async function recordProviderHealth(providerId:string,health:{ok:boolean;latencyMs:number;errorCode?:string}){const{error}=await createAdminClient().rpc("record_provider_outcome",{p_provider_id:providerId,p_ok:health.ok,p_latency_ms:health.latencyMs,p_error_code:health.errorCode??null});if(error)throw new Error("Could not record provider health");}

export async function assertProviderCircuitAvailable(providerId:string){const{data,error}=await createAdminClient().from("ai_providers").select("circuit_state,circuit_opened_at,circuit_reset_seconds").eq("id",providerId).single();if(error||!data)throw new Error("Provider health state is unavailable");if(data.circuit_state!=="open")return;const opened=data.circuit_opened_at?new Date(data.circuit_opened_at).getTime():Date.now();if(Date.now()-opened<data.circuit_reset_seconds*1000)throw new Error("Provider circuit is open");await createAdminClient().from("ai_providers").update({circuit_state:"half_open"}).eq("id",providerId).eq("circuit_state","open");}
