"use client";
import { useEffect, useMemo, useRef, useState } from "react";
type Model={id:string;display_name:string;description?:string;input_modalities:string[];capabilities:Record<string,boolean>;billing_tier:string;ai_providers:{name:string;health_status:string}};
type Conversation={id:string;title:string;is_pinned:boolean;last_message_at?:string};
type Message={id:string;role:"user"|"assistant";content:string;status?:string};
export function ChatWorkspace(){const[models,setModels]=useState<Model[]>([]);const[conversations,setConversations]=useState<Conversation[]>([]);const[messages,setMessages]=useState<Message[]>([]);const[modelId,setModelId]=useState("");const[conversationId,setConversationId]=useState<string>();const[input,setInput]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const controller=useRef<AbortController|null>(null);const selected=useMemo(()=>models.find(m=>m.id===modelId),[models,modelId]);
 useEffect(()=>{queueMicrotask(()=>{const draft=localStorage.getItem("chat-draft");if(draft)setInput(draft);});void Promise.all([fetch("/api/v1/models").then(r=>r.json()),fetch("/api/v1/conversations").then(r=>r.json())]).then(([m,c])=>{setModels(m.data??[]);setModelId(m.data?.[0]?.id??"");setConversations(c.data??[]);}).catch(()=>setError("تعذر تحميل بيانات الدردشة."));return()=>controller.current?.abort();},[]);
 useEffect(()=>{localStorage.setItem("chat-draft",input);},[input]);
 async function openConversation(id:string){setError("");const r=await fetch(`/api/v1/conversations/${id}`);const body=await r.json();if(!r.ok){setError("تعذر فتح المحادثة.");return;}setConversationId(id);setMessages((body.data.messages??[]).map((m:Message)=>m));}
 async function send(){if(!input.trim()||!modelId||busy)return;const text=input.trim();setInput("");localStorage.removeItem("chat-draft");setBusy(true);setError("");const userId=crypto.randomUUID(),assistantId=crypto.randomUUID();setMessages(v=>[...v,{id:userId,role:"user",content:text},{id:assistantId,role:"assistant",content:"",status:"streaming"}]);controller.current=new AbortController();try{const r=await fetch("/api/v1/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversationId,modelId,message:text,contentParts:[]}),signal:controller.current.signal});if(!r.ok||!r.body){const body=await r.json().catch(()=>null);throw new Error(body?.error?.message??"تعذر إرسال الرسالة.");}const reader=r.body.pipeThrough(new TextDecoderStream()).getReader();let buffer="";while(true){const{value,done}=await reader.read();if(done)break;buffer+=value;const frames=buffer.split(/\n\n/);buffer=frames.pop()??"";for(const frame of frames){const event=frame.match(/^event: (.+)$/m)?.[1];const data=frame.match(/^data: (.+)$/m)?.[1];if(!data)continue;const payload=JSON.parse(data);if(event==="meta"){setConversationId(payload.conversationId);continue;}if(event==="delta"){setMessages(v=>v.map(m=>m.id===assistantId?{...m,content:m.content+(payload.content??"")}:m));}if(event==="error")setError(`${payload.error?.message??"تعذر التوليد"} (${payload.error?.errorId??""})`);}}setMessages(v=>v.map(m=>m.id===assistantId?{...m,status:"completed"}:m));void fetch("/api/v1/conversations").then(r=>r.json()).then(v=>setConversations(v.data??[]));}catch(e){if((e as Error).name!=="AbortError")setError(e instanceof Error?e.message:"تعذر إرسال الرسالة.");setMessages(v=>v.map(m=>m.id===assistantId?{...m,status:"failed"}:m));}finally{setBusy(false);controller.current=null;}}
 function stop(){controller.current?.abort();setBusy(false);}
 return <div className="chat-grid"><aside className="chat-list"><button className="button primary" onClick={()=>{setConversationId(undefined);setMessages([]);}}>محادثة جديدة</button><div className="stack">{conversations.map(c=><button className="conversation-button" key={c.id} onClick={()=>void openConversation(c.id)}>{c.is_pinned?"★ ":""}{c.title}</button>)}</div></aside><section className="chat-panel"><div className="chat-toolbar"><label>النموذج<select value={modelId} onChange={e=>setModelId(e.target.value)}>{models.map(m=><option key={m.id} value={m.id}>{m.display_name} — {m.ai_providers.name} ({m.billing_tier})</option>)}</select></label>{selected&&<small>{selected.input_modalities.join("، ")} · {selected.ai_providers.health_status}</small>}</div><div className="messages" aria-live="polite">{messages.length===0&&<div className="empty-state">ابدأ محادثة خاصة. لن يُرسل الطلب قبل اختيار نموذج مفعّل ومفتاح صالح.</div>}{messages.map(m=><article className={`message ${m.role}`} key={m.id}><strong>{m.role==="user"?"أنت":"المساعد"}</strong><pre>{m.content||(m.status==="streaming"?"":"تعذر إنشاء الرد.")}</pre>{m.role==="assistant"&&m.content&&<button className="link-button" onClick={()=>void navigator.clipboard.writeText(m.content)}>نسخ</button>}</article>)}</div>{error&&<p className="error-state">{error}</p>}<div className="composer"><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="اكتب رسالتك…" maxLength={100000}/>{busy?<button className="button danger" onClick={stop}>إيقاف</button>:<button className="button primary" onClick={()=>void send()} disabled={!modelId||!input.trim()}>إرسال</button>}</div></section></div>}
