import { getSupabaseServerClient, requirePermission } from "@/lib/auth/guards";
const PAGE_SIZE=20;
export default async function UsersPage({searchParams}:{searchParams:Promise<{q?:string;status?:string;page?:string}>}){
  await requirePermission("users.read");const params=await searchParams;const page=Math.max(1,Number(params.page)||1);const from=(page-1)*PAGE_SIZE;
  const supabase=await getSupabaseServerClient();let query=supabase.from("profiles").select("id,display_name,username,account_status,last_seen_at,created_at,user_roles(roles(name))",{count:"exact"});
  if(params.q){const clean=params.q.replace(/[%_,]/g,"");query=query.or(`display_name.ilike.%${clean}%,username.ilike.%${clean}%`);}if(params.status&&["active","suspended","disabled"].includes(params.status))query=query.eq("account_status",params.status);
  const {data,error,count}=await query.order("created_at",{ascending:false}).range(from,from+PAGE_SIZE-1);const pages=Math.max(1,Math.ceil((count??0)/PAGE_SIZE));
  return <section><form className="filter-bar"><input name="q" defaultValue={params.q} placeholder="ابحث بالاسم أو اسم المستخدم"/><select name="status" defaultValue={params.status??""}><option value="">كل الحالات</option><option value="active">نشط</option><option value="suspended">موقوف</option><option value="disabled">معطل</option></select><button className="button primary">بحث</button></form>{error?<p className="notice">تعذر تحميل المستخدمين بأمان.</p>:<div className="data-table"><div className="table-row table-head"><b>المستخدم</b><b>الحالة</b><b>الدور</b><b>آخر ظهور</b></div>{(data??[]).map(user=><div className="table-row" key={user.id}><span>{user.display_name||user.username||"مستخدم"}<small>{user.username}</small></span><span className="status-badge">{user.account_status}</span><span>{user.user_roles?.flatMap(item=>item.roles?.map(role=>role.name)??[]).join("، ")||"user"}</span><span>{user.last_seen_at?new Date(user.last_seen_at).toLocaleDateString("ar"):"—"}</span></div>)}</div>}<nav className="pagination"><a className="button secondary" aria-disabled={page<=1} href={`?page=${Math.max(1,page-1)}`}>السابق</a><span>{page} / {pages}</span><a className="button secondary" aria-disabled={page>=pages} href={`?page=${Math.min(pages,page+1)}`}>التالي</a></nav></section>;
}
